using System.Text.Json.Serialization;

namespace CoreLibrary.Models;

public record FlashcardNoteEditablePart
{
    // A studied word in the source language (like 'la manzana', 'verde', "hojas") or idiom (like 'tener miedo')
    // With no guarantees about the form of the word (e.g., it can be singular or plural, with or without an article)
    [JsonPropertyName("term")]
    public string Term { get; set; }

    // A filesystem path to the recording of a term (in the source language)
    [JsonPropertyName("termAudio")]
    public string TermAudio { get; set; }

    // Term's translation to the target language.
    [JsonPropertyName("termTranslation")]
    public string TermTranslation { get; set; }

    // A filesystem path to the recording of a term's translation (in the target language)
    [JsonPropertyName("termTranslationAudio")]
    public string TermTranslationAudio { get; set; }

    // An example of usage of the term in a context (context is a single sentence or other minimal fragment of text)
    [JsonPropertyName("context")]
    public string Context { get; set; }

    [JsonPropertyName("contextAudio")]
    public string ContextAudio { get; set; }

    // A translation of the context to the target language
    [JsonPropertyName("contextTranslation")]
    public string ContextTranslation { get; set; }

    [JsonPropertyName("contextTranslationAudio")]
    public string ContextTranslationAudio { get; set; }

    // A relative path to the selected image from the list of image candidates.
    // Or null if no image was explicitly selected by deck author.
    [JsonPropertyName("selectedImageIndex")]
    public int? SelectedImageIndex { get; set; }

    // Additional remarks left from deck author to the student
    [JsonPropertyName("remarks")]
    public string Remarks { get; set; }

    [JsonPropertyName("qaSuggestions")]
    public string QaSuggestions { get; set; }
}

public record FlashcardNote : FlashcardNoteEditablePart
{
    // A base (standardized) form of the term (e.g. for 'manzanas' it would be 'la manzana', for 'verdes' it would be 'verde')
    [JsonPropertyName("termBaseForm")]
    public string TermBaseForm { get; set; }

    // Term's standardized form translation to English.
    // Always present, regardless of the target language - it's useful for generating images with AI models.
    [JsonPropertyName("termEnglishTranslation")]
    public string TermStandardizedFormEnglishTranslation { get; set; }


    // A translation of the context to English (always present, regardless of the target language)
    [JsonPropertyName("contextEnglishTranslation")]
    public string ContextEnglishTranslation { get; set; }

    // A part of speech which the term represents in a sentence.
    // If word has multiple meanings (e.g., a cut, to cut), then each part of speech is a separate flashcard.
    [JsonPropertyName("type")]
    public PartOfSpeech Type { get; set; }

    // List of filesystem paths to images that represent the term (ideally, also the context=example sentence).
    // A single image must be manually selected by human due to large variety in quality of images generated by AI models.
    [JsonPropertyName("imageCandidates")]
    public List<string> ImageCandidates { get; set; } = new();

    [JsonPropertyName("overrides")]
    public FlashcardNoteEditablePart? Overrides { get; set; }

    [JsonPropertyName("approvalStatus")]
    public ApprovalStatus ApprovalStatus { get; set; }

}
